webnotes/info/urls.py
from django.urls import path
from .views import *

app_name = "notes"
urlpatterns = [
    path('', InfoView.as_view(), name='index'),
]

webnotes/notes/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required

app_name = "notes"
urlpatterns = [
    path('', MyNotes.as_view(), name='index'),
    path('new', CreateNote.as_view(), name="new"),
    path('trash', TrashCanView.as_view(), name="trash"),
    path('<int:pk>', ChangeNote.as_view(), name="note"),
    path('delete/<int:pk>', DeleteNote.as_view(), name="delete"),
    path('change_favourites/<int:pk>', ChangeFavourites.as_view(), name="change_favourites"),
    path('to_trash/<int:pk>', ToTrashCan.as_view(), name="to_trash"),
    path('recover/<int:pk>', RecoverNote.as_view(), name="recover"),
]

webnotes/webnotes/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('notes.urls')),
    path('notes/', include('notes.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('info/', include('info.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webnotes/notes/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session

class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    session = models.ForeignKey(Session, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField('Название заметки', max_length=100, blank=True)
    text = models.TextField('Текст заметки', max_length=1000, blank=True)
    favourites = models.BooleanField('Добавить в избранное', default=False, blank=True)
    date_update = models.DateTimeField('Дата последнего изменения', auto_now=True)
    date_create = models.DateTimeField('Дата создания', auto_now_add=True) 
    date_to_trash = models.DateTimeField('Дата удаления', blank=True, null=True)

    def favourites_is_checked(self):
        if self.favourites == 1:
            return "checked"
        else:
            return ""

    def date_missing_string(self):
        if self.date_to_trash is not None:
            return self.date_to_trash.strftime("%Y-%m-%dT%H:%M")
        else:
            return ""
    
    def to_trash(self):
        self.date_to_trash = datetime.now()
    
    def out_of_trash(self):
        self.date_to_trash = None
    
    def in_trash(self):
        if self.date_to_trash is not None:
            if self.date_to_trash < datetime.now():
                return True
        else:
            return False

    def change_favourites(self):
        if self.favourites:
            self.favourites = False
        else:
            self.favourites = True
    
    class Meta:
        verbose_name = "Заметка"
        verbose_name_plural = "Заметки"

webnotes/notes/forms.py
from django.forms import ModelForm
from .models import Note

class NoteForm(ModelForm):
    class Meta:
        model = Note 
        fields = ['name', 'text', 'favourites']

webnotes/notes/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from notes.models import Note
from django.views import View
from django.urls import reverse
from notes.methods import *

class MyNotes(View):
    @message_for_anonymous
    def get(self, request):
        available_sort_params = ['date_update', 'date_create', 'date_to_trash']

        sort_param = get_sort_param(request, available_sort_params)
        select_param = get_select_param(sort_param, available_sort_params)
        instance = get_instance(request)
        notes = get_notes_for_user(instance, sort_param)

        current_notes = notes
        current_notes_ids = [n.id for n in current_notes if not n.in_trash()]
        current_notes = notes.filter(id__in=current_notes_ids).values_list('name', 'id', 'favourites', named=True)

        data = {
            'notes': current_notes,
            'select_param':select_param,
            }
        return render(request, 'notes/my_notes.html', data)

class TrashCanView(View):
    @message_for_anonymous
    def get(self, request):
        available_sort_params = ['date_update', 'date_create', 'date_to_trash']

        sort_param = get_sort_param(request, available_sort_params)
        select_param = get_select_param(sort_param, available_sort_params)
        instance = get_instance(request)
        notes = get_notes_for_user(instance, sort_param)

        missed_notes = notes
        missed_notes_ids = [n.id for n in missed_notes if n.in_trash()]
        missed_notes = notes.filter(id__in=missed_notes_ids).values_list('name', 'id', 'favourites', named=True)

        data = {
            'notes': missed_notes,
            'select_param':select_param,
            'trash': True,
            }
        return render(request, 'notes/my_notes.html', data)

class CreateNote(View):
    def post(self, request):
        payload = request.POST.dict()
        note = Note()

        instance = get_instance(request)
        instance.note_set.add(add_data_from_payload(note, payload))
        return HttpResponseRedirect('/notes/')
    
    @message_for_anonymous
    def get(self, request):
        data = {
            "legend":"Новая заметка",
            "new": True,
        }
        return render(request, 'notes/change_note.html', data)

class ChangeNote(View):
    def post(self, request, pk):
        instance = get_instance(request)
        note = get_object_or_404(instance.note_set, id=pk)

        payload = request.POST.dict()
        add_data_from_payload(note, payload)
        return HttpResponseRedirect('/notes/')

    @message_for_anonymous
    def get(self, request, pk):
        instance = get_instance(request)
        note = get_object_or_404(instance.note_set, id=pk)

        data = {
            'note': note,
            'legend': "Редактирование заметки",
        }
        return render(request, 'notes/change_note.html', data)

class DeleteNote(View):
    def post(self, request, pk):
        instance = get_instance(request)
        note = get_object_or_404(instance.note_set, id=pk)

        note.delete()
        return HttpResponseRedirect(reverse('notes:index'))

class ChangeFavourites(View):
    def post(self, request, pk):
        instance = get_instance(request)
        note = get_object_or_404(instance.note_set, id=pk)

        note.change_favourites()
        note.save()
        return HttpResponseRedirect('/notes/')

class RecoverNote(View):
    def post(self, request, pk):
        instance = get_instance(request)
        note = get_object_or_404(instance.note_set, id=pk)

        note.out_of_trash()
        note.save()
        return HttpResponseRedirect('/notes/trash')

class ToTrashCan(View):
    def post(self, request, pk):
        instance = get_instance(request)
        note = get_object_or_404(instance.note_set, id=pk)

        note.to_trash()
        note.save()
        return HttpResponseRedirect('/notes/')

webnotes/templates/notes/change_note.html
{% extends './../layout.html' %}
{% block content %}

<div class="mx-auto col-xs-12 col-sm-11 col-md-10 col-lg-9 col-xl-7 my-2 p-2">
	{% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
	
	<form method="POST" action="" class="mb-2" id="edit">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom border-warning mb-2">{{ legend }}</legend>

			<label for="name-note" class="form-label">Название заметки</label>
			<input type="text" class="form-control" value="{{ note.name }}" id="name-note" name="name">

			<label for="text-note" class="form-label">Текст заметки</label>
			<textarea class="form-control" id="text-note" rows="7" name="text" style="overflow: hidden">{{ note.text }}</textarea>

			<div class="form-check">
				<input class="form-check-input" type="checkbox" value="{{ True }}" id="check-favourites" name="favourites" {{ note.favourites_is_checked }}>
				<label class="form-check-label" for="check-favourites">В избранное</label>
			</div>

			<div class="d-flex flex-column">
				<label for="date" class="form-label">Дата автоматического удаления</label>
				<input type="datetime-local" id="date" name="date_missing" style="width: 200px" value="{{ note.date_missing_string }}">
			</div>
		</fieldset>
	</form>

	{% if not new %}
	<form method="post" action="{% url 'notes:delete' note.id %}" class="ms-2" id="delete">
		{% csrf_token %}
	</form>
	{% endif %}

	<div class="d-flex flex-row justify-content-end">
		<div class="me-auto">
			<a class="btn btn-outline-dark mt-2 align-self-end" href="{% url 'notes:index' %}"><i class="bi bi-arrow-left me-1"></i>Назад</a>
		</div>

		<div class="form-group ms-2">
			<input class="btn btn-primary mt-2 align-self-end" type="submit" value="Сохранить" form="edit">
		</div>

		{% if not new %}
		<div class="form-group ms-2">
			<input class="btn btn-danger mt-2 align-self-end" type="submit" value="Удалить" form="delete">
		</div>
		{% endif %}
	</div>

	{% if not new %}
	<div class="mt-1">
		<p class="dark">Создано: <span class="fw-bold">{{ note.date_create }}</span> пользователем <span class="fw-bold">{{ note.user }}</span></p>
		<p class="dark">Последнее изменение: <span class="fw-bold">{{ note.date_update }}</span></p>
	</div>
	{% endif %}
</div>

<script>
var textarea = document.querySelector('textarea');
textarea.style.height = textarea.scrollHeight + "px";
textarea.addEventListener('keyup', function(){
	if(this.scrollTop > 0){
		this.style.height = this.scrollHeight + "px";
	}
});
</script>
{% endblock %}

webnotes/templates/notes/my_notes.html
{% extends './../layout.html' %}
{% load static %}
{% block content %}

<div class="m-3 px-2 col-xs-12 col-sm-11 col-md-10 col-lg-9 col-xl-7 mx-auto d-flex flex-column">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    
    <div class="my-2 p-1 d-flex flex-wrap justify-content-md-evenly justify-content-center align-items-center border border-warning rounded">
        {% if not trash %}
        <a href='new' class="btn btn-outline-dark btn-sm me-2">+ Создать</a>
        {% endif %}

        {% if not trash %}
        <a href="trash" class="btn btn-outline-dark btn-sm"><i class="bi bi-trash me-1"></i>Корзина</a>
        {% endif %}

        {% if trash %}
        <a href={% url 'notes:index' %} class="btn btn-sm btn-outline-dark"><i class="bi bi-arrow-left me-1"></i>Назад</a>
        {% endif %}
        <form action="" class="d-flex justify-content-sm-center m-1">
            <div class="input-group input-group-sm">
                <span class="input-group-text"><i class="bi bi-funnel"></i></span>

                <select class="form-select form-control" name="sort">
                    <option value="date_update" {{ select_param.date_update }}>Дата обновления</option>
                    <option value="date_create" {{ select_param.date_create }}>Дата создания</option>
                    {% if trash %}
                    <option value="date_to_trash" {{ select_param.date_to_trash }}>Дата удаления</option>
                    {% else %}
                    <option value="date_to_trash" {{ select_param.date_to_trash }}>Дата автоматич. удаления</option>
                    {% endif %}
                </select>

                <input type="checkbox" class="btn-check" id="sort-reverse" autocomplete="off" name="reverse" value="true">
                <label class="btn btn-outline-dark" for="sort-reverse"><i class="bi bi-arrow-down-up"></i></label>

                <button class="btn btn-outline-dark btn-sm" type="submit">Применить</button>
            </div>
        </form>
    </div>

{% for note in notes %}
    <div class="my-1 p-2 d-flex flex-row align-items-center border border-dark rounded">
        {% if note.favourites == True %}
            <div class="star me-2"></div>
        {% endif %}

        <a class="flex-grow-1 text-break text-dark ms-2" style="text-decoration: none" href={% url 'notes:note' note.id %}>{{ note.name }}</a>

        {% if not trash %}
        <form method="post" action="{% url 'notes:change_favourites' note.id %}" class="ms-2">
            {% csrf_token %}
            <button type="submit" style="border: none; background: none"><a href=""><i class="bi bi-star"></i></a></button>
        </form>

        <a href={% url 'notes:note' note.id %} class="ms-2"><i class="bi bi-pencil-square"></i></a>

        <form method="post" action="{% url 'notes:to_trash' note.id %}" class="ms-2">
            {% csrf_token %}
            <button type="submit" style="border: none; background: none"><a href=""><i class="bi bi-trash"></i></a></button>
        </form>
        
        {% else %}
        <form method="post" action="{% url 'notes:recover' note.id %}" class="ms-2">
            {% csrf_token %}
            <button type="submit" style="border: none; background: none"><a href=""><i class="bi bi-arrow-counterclockwise"></i></a></button>
        </form>

        <form method="post" action="{% url 'notes:delete' note.id %}" class="ms-2">
            {% csrf_token %}
            <button type="submit" style="border: none; background: none"><a href=""><i class="bi bi-x-circle-fill"></i></a></button>
        </form>
        {% endif %}
    </div>
{% endfor %}
</div>

<style>
    .star {
        width: 20px;
        height: 20px;
        background-repeat: no-repeat;
        background-size: contain;
        background-image: url("{% static 'icons/star.png' %}");
    }
</style>
{% endblock %}